### ISSUE TITLE
When carousel on small screen and cover whole screen cannot scroll/swipe down page

### ISSUE THREAD

**Issue by Lechus** [maaaaark/bcSwipe#1]
Hi,

Nice plugin, works with BS 3.3.4.
On small devices, when carousel takes whole screen (view) user cannot swipe/scroll page down.

Is there a chance to add ignore swipe down/up?

Cheers

**Comment by maaaaark** [comment]
Yes, I have updated the readme to show how to do this. Set `preventDefaultEvents` to `false` and scrolling will be back to normal.

**Comment by maaaaark** [comment]
Actually, I have updated the code and removed the option to capture up and down swipes, as it's really not necessary for Bootstrap carousels. So I recommend downloading the latest version of this plugin.

**Comment by Lechus** [comment]
Thanks!
